# language: objective-c  #1
# osx_image: xcode7 #2
# xcode_project: Sortanim.xcodeproj #3
# xcode_scheme: Sortanim #4
# xcode_sdk: iphonesimulator8.3 #5

# language: objective-c
# osx_image: xcode7.3
# env:
#   - SCHEME=Sortanim
# matrix:
#   fast_finish: true
#   allow_failures:
#     - env: SCHEME=Sortanim

# before_script:
  # - sudo systemsetup -settimezone America/Los_Angeles
# use script to run tests, instead of default script that does 'xctool build test'
# script:
  # - travis_retry ./scripts/travis-script.sh
# after_failure:
  # - bundle exec scripts/upload-screenshots.rb
# after_success:
  # - ls -latr test_screenshots/\*line\* || bundle exec scripts/upload-screenshots.rb


# language: objective-d
# before_install:
    # - brew update
    # - brew install xctool
script:
    - travis_retry ./scripts/travis-script.sh